package com.example.unipazar

object UniversityData {
    val universities = listOf(
        "Tüm Üniversiteler",
        "Abant İzzet Baysal Üniversitesi",
        "Acıbadem Üniversitesi",
        "Adnan Menderes Üniversitesi",
        "Afyon Kocatepe Üniversitesi",
        "Ağrı İbrahim Çeçen Üniversitesi",
        "Ahi Evran Üniversitesi",
        "Akdeniz Üniversitesi",
        "Aksaray Üniversitesi",
        "Amasya Üniversitesi",
        "Anadolu Üniversitesi",
        "Ankara Üniversitesi",
        "Ankara Hacı Bayram Veli Üniversitesi",
        "Ankara Sosyal Bilimler Üniversitesi",
        "Antalya Bilim Üniversitesi",
        "Ardahan Üniversitesi",
        "Artvin Çoruh Üniversitesi",
        "Atatürk Üniversitesi",
        "Atılım Üniversitesi",
        "Aydın Adnan Menderes Üniversitesi",
        "Bahçeşehir Üniversitesi",
        "Balıkesir Üniversitesi",
        "Bandırma Onyedi Eylül Üniversitesi",
        "Bartın Üniversitesi",
        "Başkent Üniversitesi",
        "Batman Üniversitesi",
        "Bayburt Üniversitesi",
        "Beykent Üniversitesi",
        "Bezmialem Vakıf Üniversitesi",
        "Bilecik Şeyh Edebali Üniversitesi",
        "Bingöl Üniversitesi",
        "Bitlis Eren Üniversitesi",
        "Boğaziçi Üniversitesi",
        "Bozok Üniversitesi",
        "Bursa Teknik Üniversitesi",
        "Bursa Uludağ Üniversitesi",
        "Çağ Üniversitesi",
        "Çanakkale Onsekiz Mart Üniversitesi",
        "Çankaya Üniversitesi",
        "Çankırı Karatekin Üniversitesi",
        "Çukurova Üniversitesi",
        "Dicle Üniversitesi",
        "Doğuş Üniversitesi",
        "Dokuz Eylül Üniversitesi",
        "Düzce Üniversitesi",
        "Ege Üniversitesi",
        "Erciyes Üniversitesi",
        "Erzincan Binali Yıldırım Üniversitesi",
        "Erzurum Teknik Üniversitesi",
        "Eskişehir Osmangazi Üniversitesi",
        "Eskişehir Teknik Üniversitesi",
        "Fatih Sultan Mehmet Vakıf Üniversitesi",
        "Fenerbahçe Üniversitesi",
        "Fırat Üniversitesi",
        "Galatasaray Üniversitesi",
        "Gazi Üniversitesi",
        "Gaziantep Üniversitesi",
        "Gaziosmanpaşa Üniversitesi",
        "Gebze Teknik Üniversitesi",
        "Giresun Üniversitesi",
        "Gümüşhane Üniversitesi",
        "Hacettepe Üniversitesi",
        "Hakkari Üniversitesi",
        "Haliç Üniversitesi",
        "Harran Üniversitesi",
        "Hasan Kalyoncu Üniversitesi",
        "Hitit Üniversitesi",
        "Iğdır Üniversitesi",
        "Isparta Uygulamalı Bilimler Üniversitesi",
        "Işık Üniversitesi",
        "İbn Haldun Üniversitesi",
        "İhsan Doğramacı Bilkent Üniversitesi",
        "İnönü Üniversitesi",
        "İskenderun Teknik Üniversitesi",
        "İstanbul Arel Üniversitesi",
        "İstanbul Aydın Üniversitesi",
        "İstanbul Bilgi Üniversitesi",
        "İstanbul Gelişim Üniversitesi",
        "İstanbul Kültür Üniversitesi",
        "İstanbul Medipol Üniversitesi",
        "İstanbul Okan Üniversitesi",
        "İstanbul Sabahattin Zaim Üniversitesi",
        "İstanbul Şehir Üniversitesi",
        "İstanbul Teknik Üniversitesi (İTÜ)",
        "İstanbul Ticaret Üniversitesi",
        "İstanbul Üniversitesi",
        "İstinye Üniversitesi",
        "İzmir Bakırçay Üniversitesi",
        "İzmir Demokrasi Üniversitesi",
        "İzmir Ekonomi Üniversitesi",
        "İzmir Katip Çelebi Üniversitesi",
        "İzmir Yüksek Teknoloji Enstitüsü",
        "Kadir Has Üniversitesi",
        "Kafkas Üniversitesi",
        "Kahramanmaraş Sütçü İmam Üniversitesi",
        "Karabük Üniversitesi",
        "Karadeniz Teknik Üniversitesi (KTÜ)",
        "Karamanoğlu Mehmetbey Üniversitesi",
        "Kastamonu Üniversitesi",
        "Kayseri Üniversitesi",
        "Kırıkkale Üniversitesi",
        "Kırklareli Üniversitesi",
        "Kırşehir Ahi Evran Üniversitesi",
        "Kilis 7 Aralık Üniversitesi",
        "Kocaeli Üniversitesi",
        "Koç Üniversitesi",
        "Konya Gıda ve Tarım Üniversitesi",
        "KTO Karatay Üniversitesi",
        "Kütahya Dumlupınar Üniversitesi",
        "Kütahya Sağlık Bilimleri Üniversitesi",
        "Lokman Hekim Üniversitesi",
        "Malatya Turgut Özal Üniversitesi",
        "Maltepe Üniversitesi",
        "Manisa Celal Bayar Üniversitesi",
        "Mardin Artuklu Üniversitesi",
        "Marmara Üniversitesi",
        "MEF Üniversitesi",
        "Mersin Üniversitesi",
        "Mimar Sinan Güzel Sanatlar Üniversitesi",
        "Muğla Sıtkı Koçman Üniversitesi",
        "Munzur Üniversitesi",
        "Muş Alparslan Üniversitesi",
        "Necmettin Erbakan Üniversitesi",
        "Nevşehir Hacı Bektaş Veli Üniversitesi",
        "Niğde Ömer Halisdemir Üniversitesi",
        "Nuh Naci Yazgan Üniversitesi",
        "Okan Üniversitesi",
        "Ondokuz Mayıs Üniversitesi",
        "Ordu Üniversitesi",
        "Orta Doğu Teknik Üniversitesi (ODTÜ)",
        "Osmaniye Korkut Ata Üniversitesi",
        "Ostim Teknik Üniversitesi",
        "Özyeğin Üniversitesi",
        "Pamukkale Üniversitesi",
        "Piri Reis Üniversitesi",
        "Recep Tayyip Erdoğan Üniversitesi",
        "Sabancı Üniversitesi",
        "Sağlık Bilimleri Üniversitesi",
        "Sakarya Uygulamalı Bilimler Üniversitesi",
        "Sakarya Üniversitesi",
        "Samsun Üniversitesi",
        "Sanko Üniversitesi",
        "Selçuk Üniversitesi",
        "Siirt Üniversitesi",
        "Sinop Üniversitesi",
        "Sivas Cumhuriyet Üniversitesi",
        "Süleyman Demirel Üniversitesi",
        "Şırnak Üniversitesi",
        "Tarsus Üniversitesi",
        "TED Üniversitesi",
        "Tekirdağ Namık Kemal Üniversitesi",
        "TOBB Ekonomi ve Teknoloji Üniversitesi",
        "Tokat Gaziosmanpaşa Üniversitesi",
        "Toros Üniversitesi",
        "Trabzon Üniversitesi",
        "Trakya Üniversitesi",
        "Türk-Alman Üniversitesi",
        "Ufuk Üniversitesi",
        "Uşak Üniversitesi",
        "Üsküdar Üniversitesi",
        "Van Yüzüncü Yıl Üniversitesi",
        "Yalova Üniversitesi",
        "Yaşar Üniversitesi",
        "Yeditepe Üniversitesi",
        "Yeniyüzyıl Üniversitesi",
        "Yıldız Teknik Üniversitesi (YTÜ)",
        "Yozgat Bozok Üniversitesi",
        "Zonguldak Bülent Ecevit Üniversitesi"
    )
}
